### ISSUE TITLE
Id should not be a MathOperator

### ISSUE THREAD

**Issue by mathurinm** [josephsalmon/OrganizationFiles#33]
It induces wrong spacing when you do `$\Id + A$`  (space after + is too small)
![image](https://github.com/josephsalmon/OrganizationFiles/assets/8993218/fcf8ce5a-8f8a-4af4-af51-a16798004d41)

https://tex.stackexchange.com/questions/273834/spacing-using-operators

turns out the correct command is \newcommand{\Id}{{\rm Id}}
![image](https://github.com/josephsalmon/OrganizationFiles/assets/8993218/2592144d-0fd2-4af7-a662-e362d40cb24c)

**Comment by josephsalmon** [comment]
Thanks  for the feedback.
now corrected in `shortcut_js.sty`.
